//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class saloondbEntities : DbContext
    {
        public saloondbEntities()
            : base("name=saloondbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcheckin> checkins { get; set; }
        public virtual DbSet<tblrole> roles { get; set; }
        public virtual DbSet<tblsaloonuser> saloonusers { get; set; }
        public virtual DbSet<tbluser> users { get; set; }
    }
}
