//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;


    public partial class tblcheckin
    {
        public int id { get; set; }
        public Nullable<System.DateTime> checkin_time { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public int saloon_id { get; set; }
        public int user_id { get; set; }
        public int role_id { get; set; }

        [JsonIgnore]
        public virtual tblsaloonuser tblsaloonuser { get; set; }
        [JsonIgnore]
        public virtual tbluser tbluser { get; set; }
        [JsonIgnore]
        public virtual tblrole tblrole { get; set; }
    }
}
