//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsaloonuser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblsaloonuser()
        {
            this.tblcheckins = new HashSet<tblcheckin>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string Address { get; set; }
        public string email { get; set; }
        public string zipcode { get; set; }
        public string saloon_name { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public int role_id { get; set; }
        public Nullable<System.TimeSpan> businesshrs_from { get; set; }
        public Nullable<System.TimeSpan> businesshrs_to { get; set; }
        public double lattitude { get; set; }
        public double longitude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcheckin> tblcheckins { get; set; }
        public virtual tblrole tblrole { get; set; }
    }
}
